#!/usr/bin/env Rscript
require(plotrix)
circledata <- read.table('00064results0.txt')
xmin = min(c(circledata$V1, circledata$V3, circledata$V5))
xmax = max(c(circledata$V1, circledata$V3, circledata$V5))
ymin = min(c(circledata$V2, circledata$V4, circledata$V6))
ymax = max(c(circledata$V2, circledata$V4, circledata$V6))
xlow = xmin - 0*(xmax-xmin)
xhig = xmax + 0*(xmax-xmin)
ylow = ymin - 0*(ymax-ymin)
yhig = ymax + 0*(ymax-ymin)
plot(circledata$V7, circledata$V8, xlim=c(xlow, xhig), ylim=c(ylow, yhig),  pch=19, cex=0.4, col="blue", asp=1)
par(new=T)
plot(circledata$V1, circledata$V2, xlim=c(xlow, xhig), ylim=c(ylow, yhig),  pch=19, cex=0.5, col="red", asp=1)
par(new=T)
plot(circledata$V3, circledata$V4, xlim=c(xlow, xhig), ylim=c(ylow, yhig),  pch=19, cex=0.5, col="red", asp=1)
par(new=T)
plot(circledata$V5, circledata$V6, xlim=c(xlow, xhig), ylim=c(ylow, yhig),  pch=19, cex=0.5, col="red", asp=1)
par(new=T)
for (i in 1:length(circledata$V9)) {
    draw.circle(circledata$V7[i], circledata$V8[i], circledata$V9[i])
}
verifyradius = sqrt((circledata$V5-circledata$V7)**2+(circledata$V6-circledata$V8)**2)
radiusdiff = abs(circledata$V9-verifyradius)
summary(radiusdiff)
